### ISSUE TITLE
Is there support for privacy manifest requirements from Apple?

### ISSUE THREAD

**Issue by spqw** [googleads/swift-package-manager-google-mobile-ads#67]
Hi, 

Is there support for privacy manifest requirements from Apple?

When trying to integrate Google Mobile Ads in a sample project, there is no entry related to Google Mobile Ads in the generated privacy report. Is that expected?

I see that a `xcprivacy` file was introduced on Nov 2023 with the following [commit](https://github.com/googleads/swift-package-manager-google-mobile-ads/commit/516b4a782cd78462196d237e4ebe30ecbf579393), but then the commit was [reverted](https://github.com/googleads/swift-package-manager-google-mobile-ads/commit/15a69af11164c21100e3f8cd672ab3069158ee63) in Dec 2023.

Could we get an update on the latest status about the support for privacy manifest from Apple?

**Comment by malandr2** [comment]
Hi @spqw, our next release `11.2.0` is expected to have to support for privacy manifest files.

**Comment by ashtl** [comment]
> Hi @spqw, our next release `11.2.0` is expected to have to support for privacy manifest files.

Do you know when that release is scheduled for?

**Comment by ericleich** [comment]
It is live as of yesterday.

**Comment by talaviram** [comment]
I've uploaded an app yesterday using 11.2.0 and got warnings about:

- NSPrivacyAccessedAPICategoryDiskSpace
- NSPrivacyAccessedAPICategoryUserDefaults

UserDefaults is expected also on my app, but the Disk Space I suspect is due to AdMob. I should also declare it on my app or the lib was already suppose to be sufficient?

(note the app I've uploaded had no Privacy Manifest)
